### ISSUE TITLE
Not working on QPR2 Beta 3.2 (Pixel6)

### ISSUE THREAD

**Issue by hsoc** [kyujin-cho/pixel-volte-patch#68] opened 2023-02-28 17:55 UTC
Latest beta (QPR2 Beta 3.2) in Greece includes Carrier settings version: telekom_gr-43000000001.58 (2023-01-06)
In this version VoLTE option is already shown and working.
Using the patch shows wifi and carrier video calling but it doesn't work.

 - Device: Pixel 6
 - OS: Android 13
 - Version T2B3.230109.009

**Comment by kyujin-cho** [comment] 2023-03-04 13:47
Duplicate of #61.

**Comment by hsoc** [comment] 2023-04-10 06:17
I just like to mention that this issue was fixed on latest version (probaly earlier too) for my carrier (GR-Cosmote) after adding  a new APN (ims/ims). 
Please close.

**Closed** 2023-05-21 07:15 UTC
