### ISSUE TITLE
Backup calling gone in Android 14

### ISSUE THREAD

**Issue by saltajose** [kyujin-cho/pixel-volte-patch#196] opened 2023-10-12 20:10 UTC
Backup Calling toggle does nothing. It could be that this has been removed with Android 14. I can't yet confirm this is the case.

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14 stable, october 2023 security patch

**Comment by gdlbu** [comment] 2023-10-24 03:49
As a Pixel 8 Pro user, I am eagerly looking forward to being able to use Backup Calling smoothly.

**Comment by huajijam** [comment] 2023-10-27 10:07
https://cs.android.com/android/platform/superproject/+/android-14.0.0_r2:frameworks/base/telephony/java/android/telephony/CarrierConfigManager.java

the keys are still in Android 14,not sure why not working

**Comment by xantrk** [comment] 2023-11-13 00:34
https://android.googlesource.com/platform/packages/apps/Settings/+/812b59b981ddb2b09e44880424ad3e010fbecc08

They removed it for pixel, but this implies the feature is still there possibly.

**Comment by garacio** [comment] 2023-11-15 22:37
[This](https://support.google.com/pixelphone/thread/238939661?hl=en&msgid=238980033) helps me.
Just turned on _Switch mobile data automatically_ switcher

**Comment by garacio** [comment] 2023-11-16 08:30
> [This](https://support.google.com/pixelphone/thread/238939661?hl=en&msgid=238980033) helps me. Just turned on _Switch mobile data automatically_ switcher

And stops working after today's  security update (

**Comment by garacio** [comment] 2023-11-17 07:35
> > [This](https://support.google.com/pixelphone/thread/238939661?hl=en&msgid=238980033) helps me. Just turned on _Switch mobile data automatically_ switcher
> 
> And stops working after today's security update (

**Comment by kyujin-cho** [comment] 2023-11-28 11:14
Closing since the issue is derived from upstream Android changes; please feel free to reopen if situation changes.

**Closed by kyujin-cho** 2023-11-28 11:14 UTC

**Comment by Batmanoulis** [comment] 2023-12-15 23:32
Will it be enabled again? I see the option in ims but not in the phones settings and of course i lose my connection when I am on call...

**Comment by fillwithjoy1** [comment] 2024-02-24 14:23
Clearer guide on what to do (eSIM, pSIM doesn't matter)
When I refer to the `Data SIM` we are talking about the local sim that has internet available
When I refer to the `Calling SIM` we are talking about the roaming sim that has Wi-Fi Calling available (VoWIFI). If your carrier didn't have Wi-Fi calling working (test with airplane mode) before you travelled, this won't work.

1. On your `Calling SIM` enable these toggles
- `Enable VoLTE`
- `Enable Backup Calling`
- `Enable VoWiFi`
- `Enable VoWiFi while roaming`

cosmetic wise, you can enable these
- `Show VoWiFi preference in Settings`
- `Show VoWiFi Roaming preference in Settings`
- `Show VoWiFi Icon`

2. Once you have done these go to your `Calling SIM` settings and enable `Switch mobile data automatically` (screenshot provided)
You **don't need to enable Roaming or Mobile data**
![Screenshot_20240224-192317](https://github.com/kyujin-cho/pixel-volte-patch/assets/29514446/92ba0541-a267-438c-a7fd-42124a2aee53)

3. Restart your phone
4. You should observe your `Calling SIM` showing "Backup calling". It doesn't have to be connected yet (screenshots below, my `Data SIM` is Jio and you'll notice calling anyone with `Calling SIM` reports no signal).
![Screenshot_20240224-192339](https://github.com/kyujin-cho/pixel-volte-patch/assets/29514446/f075e147-a7f2-43ea-9392-eacade30fb07)
![Screenshot_20240224-192921](https://github.com/kyujin-cho/pixel-volte-patch/assets/29514446/dcbefcc0-385b-4c47-b854-088499e4d929)

6. Eventually your Calling SIM should connect successfully.

# Troubleshooting
## My `Calling SIM` is stuck on "Backup calling" but doesn't connect in the end.
For me, I found out that my `Data SIM` 5G mode didn't allow Wi-Fi calling (I tested this out with 2 handsets) and so I had to switch to 4G for it to finally work

## My `Calling SIM` switches to No Service / Emergency calls only after a while
Your `Data SIM` might not have good internet. You can reset this by going into `Pixel IMS` and going into your `Calling SIM` page and hitting `Restart IMS registration`

I will close this by saying that when it works, just leave it as is. It seems quite easy to break regardless.
